project:
  type: website
  output-dir: docs
  resources:
    - "Allen_Vita.pdf"
  render:
    - "*.qmd"
    - "*.md"
freeze: auto



website:
  title: ""
  site-url: "https://joshuafayallen.github.io"
  repo-url: "https://github.com/joshuafayallen/quarto-website"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        file: research/index.qmd
      - text: "Teaching"
        file: teaching/index.qmd
      - text: "CV"
        file: CV/index.qmd
      - text: "Blog"
        file: blog/index.qmd
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:joshua.f.allen@gmail.com"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/joshuallen17
      - icon: github
        aria-label: github
        href: https://github.com/joshuafayallen
format:
  html:
    theme: 
      - allen.scss
    toc: true
knitr: 
  opts_chunk: 
    engine.path:
      python: `r file.path(here::here(), '.venv', 'bin', "python")`



